### ISSUE TITLE
MYClassFromType doesn't handle model properties with protocols 

### ISSUE THREAD

**Issue by saltzmanjoelh** [snej/MYUtilities#10]
@property (weak) JSModel <JSProtocol> *someModelProp;

    Class MYClassFromType(const char* propertyType) {
        size_t len = strlen(propertyType);
        if (propertyType[0] != _C_ID || propertyType[1] != '"' || propertyType[len-1] != '"')
            return NULL;
        char className[len - 2];
        strlcpy(className, propertyType + 2, len - 2);
        return objc_getClass(className);//className == "@\"JSModel<JSProtocol>\""
    }

NULL is returned

**Comment by snej** [comment]
It's not clear from the code what the actual problem is that you're describing. Could you explain it in English?

**Comment by saltzmanjoelh** [comment]
Normally, model properties do not have a protocol listed after the model class
@property (weak) JSModel *someProperty;

When you call myVar.someProperty, the framework creates an instance of JSModel instead of the documentID string.


If you add a protocol name after the model class, when you call myVar.someProperty, the documentID string is returned instead of an instance of your model class  (JSModel).
@property (weak) JSModel <JSProtocol> *someProperty;


I traced it down to the MYClassFromType function.
If you don’t have a protocol listed next to the model class in the property, the function works as expected:
objc_getClass(className);//className is the string "@\"JSModel\”"

If you do have a protocol listed next to the model class in the property, objc_getClass returns NULL:
objc_getClass(className);//className is the string "@\"JSModel<JSProtocol>\””

**Comment by snej** [comment]
Got it. But I don't think `JSModel<JSProtocol>` is a reasonable type to use for a dynamic CBLModel property — it means "a class compatible with JSModel that implements JSProtocol". If JSModel itself implements JSProtocol, then just use `JSModel` as the type. If JSModel doesn't actually implement JSProtocol but there's a subclass that does, then you'll need to explicitly declare the property as being of that subclass, otherwise CBLModel won't know to instantiate that particular subclass.

Or is there something fancy you're doing that requires you to declare the property that way? I can't figure out what it could be...

**Comment by saltzmanjoelh** [comment]
Here is a simplified example of why I would need a protocol. I have 2 different classes the implement a protocol and I want to make sure that only a class that implements the protocol gets used for the property.

![screen shot 2015-02-12 at 10 00 49 pm](https://cloud.githubusercontent.com/assets/1833492/6183032/52136768-b304-11e4-92bb-9e8ec2d519d8.png)

I added some obj-c to parse the protocol out of the property name and everything seems to be working;


    static const char* MYGetPropertyType(objc_property_t property, BOOL *outIsSettable) {
        *outIsSettable = YES;
        const char *result = "@";
    
        // Copy property attributes into a writeable buffer:
        const char *attributes = property_getAttributes(property);
        //handle protocol in property name
        const char *protocolStr = strchr(attributes, '<');
        if(protocolStr){
            NSString *attributesStr = [NSString stringWithUTF8String:attributes];
            NSInteger location = [attributesStr rangeOfString:@"<"].location;
            NSInteger length = [attributesStr rangeOfString:@">"].location - location+1;
            attributes = [attributesStr stringByReplacingCharactersInRange:NSMakeRange(location, length) withString:@""].UTF8String;
        }
        char buffer[1 + strlen(attributes)];
        strcpy(buffer, attributes);
    
        // Scan the comma-delimited sections of the string:
        char *state = buffer, *attribute;
        while ((attribute = strsep(&state, ",")) != NULL) {
            switch (attribute[0]) {
                case 'T':       // Property type in @encode format
                    result = (const char *)[[NSData dataWithBytes: (attribute + 1) 
                                                           length: strlen(attribute)] bytes];
                    break;
                case 'R':       // Read-only indicator
                    *outIsSettable = NO;
                    break;
            }
        }
        return result;
    }

**Comment by snej** [comment]
For unrelated reasons I suddenly have a need to support interface-valued properties (i.e. `@property id<Something> something`) so it looks like I'll be adopting something like your code above. Nice timing!
