### ISSUE TITLE
MYUtilities_Prefix.pch compile error

### ISSUE THREAD

**Issue by ilia510** [snej/MYUtilities#8]
I tried to use myCrypto library and followed the setup process. I just added the Xcode.proj file (my crypto) to an small cocoa app. Then change build phases adding into "Build Phases" to Target Dependencies (Static Lib Mycrypto), then to Link binary with Libraries - libMyCrypto.a.

And then just pressed Build and it fails with the following message:

clang: error: argument unused during compilation: '-fnested-functions'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

for library 
ProcessPCH /Users/ilia/Library/Developer/Xcode/DerivedData/RandomGenerator-dwnttcbneqcvxiavyzkeswjjyavp/Build/Intermediates/PrecompiledHeaders/MYUtilities_Prefix-bpigycgguxphvwclrxcajutfidce/MYUtilities_Prefix.pch.pch ../MYUtilities/MYUtilities_Prefix.pch normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

I am using OS X 10.9.5, Xcode 6.
Would please have a look and help?

**Comment by snej** [comment]
This is an issue with the target in the MYCrypto project, not with the precompiled header.
